// @generated by uor-crate from uor-ontology — do not edit manually

//! `kernel` space modules.

pub mod address;
pub mod carry;
pub mod convergence;
pub mod division;
pub mod effect;
pub mod failure;
pub mod linear;
pub mod monoidal;
pub mod op;
pub mod operad;
pub mod parallel;
pub mod predicate;
pub mod recursion;
pub mod reduction;
pub mod region;
pub mod schema;
pub mod stream;
