//! `homology/` namespace — Simplicial complexes, chain homology, and the ψ-pipeline.
//!
//! The covariant arm of structural reasoning. Defines simplicial complexes built
//! from constraint nerves, chain complexes, boundary operators, and homology groups
//! that ground Betti numbers.
//!
//! **Space classification:** `bridge` — kernel-computed, user-requested.

use crate::model::iris::*;
use crate::model::{
    Class, Individual, IndividualValue, Namespace, NamespaceModule, Property, PropertyKind, Space,
};

/// Returns the `homology/` namespace module.
#[must_use]
pub fn module() -> NamespaceModule {
    NamespaceModule {
        namespace: Namespace {
            prefix: "homology",
            iri: NS_HOMOLOGY,
            label: "UOR Homology",
            comment: "Simplicial complexes, chain complexes, boundary operators, and \
                      homology groups for structural reasoning.",
            space: Space::Bridge,
            imports: &[
                NS_SCHEMA,
                NS_TYPE,
                NS_RESOLVER,
                NS_PARTITION,
                NS_OBSERVABLE,
                NS_OP,
            ],
        },
        classes: classes(),
        properties: properties(),
        individuals: individuals(),
    }
}

fn classes() -> Vec<Class> {
    vec![
        Class {
            id: "https://uor.foundation/homology/Simplex",
            label: "Simplex",
            comment: "A k-simplex: a finite set of k+1 vertices drawn from constraint objects.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/SimplicialComplex",
            label: "SimplicialComplex",
            comment: "A simplicial complex: a set of simplices closed under taking faces.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/FaceMap",
            label: "FaceMap",
            comment: "A face map d_i: removes vertex i from a simplex, producing a face.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/ChainGroup",
            label: "ChainGroup",
            comment: "A free abelian group generated by k-simplices (the k-th chain group C_k).",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/BoundaryOperator",
            label: "BoundaryOperator",
            comment: "The boundary operator \u{2202}_k: C_k \u{2192} C_{k-1}. Satisfies \u{2202}\u{00b2} = 0.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/ChainComplex",
            label: "ChainComplex",
            comment: "A chain complex: a sequence of chain groups connected by boundary operators.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/HomologyGroup",
            label: "HomologyGroup",
            comment: "The k-th homology group H_k = ker(\u{2202}_k) / im(\u{2202}_{k+1}). \
                      Measures k-dimensional holes.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/NerveFunctor",
            label: "NerveFunctor",
            comment: "The nerve functor N: maps a set of constraints to a simplicial complex.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/ChainFunctor",
            label: "ChainFunctor",
            comment: "The chain functor C: maps a simplicial complex to a chain complex.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        // Amendment 54: Higher homotopy infrastructure
        Class {
            id: "https://uor.foundation/homology/KanComplex",
            label: "KanComplex",
            comment: "A simplicial set satisfying the Kan extension condition. The constraint \
                      nerve, when promoted from a SimplicialComplex to a KanComplex, carries a \
                      full homotopy type \u{2014} not just its homology groups.",
            subclass_of: &["https://uor.foundation/homology/SimplicialComplex"],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/HornFiller",
            label: "HornFiller",
            comment: "A witness that a given horn (an incomplete simplex boundary) can be filled, \
                      certifying the Kan condition at a specific dimension and position.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/PostnikovTruncation",
            label: "PostnikovTruncation",
            comment: "The k-th Postnikov truncation \u{03c4}\u{2264}k of the constraint nerve: a \
                      KanComplex whose homotopy groups \u{03c0}j vanish for j > k.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        Class {
            id: "https://uor.foundation/homology/KInvariant",
            label: "KInvariant",
            comment: "The k-invariant \u{03ba}k that classifies the extension from the \
                      (k\u{2212}1)-truncation to the k-truncation of the Postnikov tower. \
                      Trivial \u{03ba}k means the truncation splits as a product.",
            subclass_of: &[OWL_THING],
            disjoint_with: &[],
        },
        // Amendment 56: Deformation Complex
        Class {
            id: "https://uor.foundation/homology/DeformationComplex",
            label: "DeformationComplex",
            comment: "The deformation complex of a CompleteType T: a chain complex \
                      whose H\u{2070} = automorphisms, H\u{00b9} = first-order \
                      deformations, H\u{00b2} = obstructions to extending deformations.",
            subclass_of: &["https://uor.foundation/homology/ChainComplex"],
            disjoint_with: &[],
        },
    ]
}

fn properties() -> Vec<Property> {
    vec![
        // --- Own-domain properties (22) ---
        Property {
            id: "https://uor.foundation/homology/dimension",
            label: "dimension",
            comment: "The dimension k of a simplex (number of vertices minus one).",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/Simplex"),
            range: XSD_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/vertex",
            label: "vertex",
            comment: "A vertex of this simplex, drawn from the set of constraint objects.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/Simplex"),
            range: "https://uor.foundation/type/Constraint",
        },
        Property {
            id: "https://uor.foundation/homology/vertexCount",
            label: "vertexCount",
            comment: "The number of vertices in this simplex (dimension + 1).",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/Simplex"),
            range: XSD_POSITIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/isFaceOf",
            label: "isFaceOf",
            comment: "Indicates that this simplex is a face of another simplex.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/Simplex"),
            range: "https://uor.foundation/homology/Simplex",
        },
        Property {
            id: "https://uor.foundation/homology/pinIntersection",
            label: "pinIntersection",
            comment: "A fiber coordinate in the partition whose intersection pins this simplex.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/Simplex"),
            range: "https://uor.foundation/partition/FiberCoordinate",
        },
        Property {
            id: "https://uor.foundation/homology/hasSimplex",
            label: "hasSimplex",
            comment: "A simplex belonging to this simplicial complex.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/SimplicialComplex"),
            range: "https://uor.foundation/homology/Simplex",
        },
        Property {
            id: "https://uor.foundation/homology/maxDimension",
            label: "maxDimension",
            comment: "The maximum dimension of any simplex in this simplicial complex.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/SimplicialComplex"),
            range: XSD_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/eulerCharacteristic",
            label: "eulerCharacteristic",
            comment: "The Euler characteristic of this simplicial complex: the alternating \
                      sum of simplex counts by dimension.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/SimplicialComplex"),
            range: XSD_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/simplicialVertexCount",
            label: "simplicialVertexCount",
            comment: "The total number of vertices (0-simplices) in this simplicial complex.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/SimplicialComplex"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/removesVertex",
            label: "removesVertex",
            comment: "The index i of the vertex removed by this face map d_i.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/FaceMap"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/sourceSimplex",
            label: "sourceSimplex",
            comment: "The source simplex of this face map.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/FaceMap"),
            range: "https://uor.foundation/homology/Simplex",
        },
        Property {
            id: "https://uor.foundation/homology/targetFace",
            label: "targetFace",
            comment: "The target face (result simplex) of this face map.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/FaceMap"),
            range: "https://uor.foundation/homology/Simplex",
        },
        Property {
            id: "https://uor.foundation/homology/degree",
            label: "degree",
            comment:
                "The degree k of this chain group (the dimension of its generating simplices).",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/ChainGroup"),
            range: XSD_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/rank",
            label: "rank",
            comment: "The rank of a free abelian group (number of generators).",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: None,
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/generatedBy",
            label: "generatedBy",
            comment: "A simplex that generates this chain group.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/ChainGroup"),
            range: "https://uor.foundation/homology/Simplex",
        },
        Property {
            id: "https://uor.foundation/homology/sourceGroup",
            label: "sourceGroup",
            comment: "The source chain group C_k of this boundary operator.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/BoundaryOperator"),
            range: "https://uor.foundation/homology/ChainGroup",
        },
        Property {
            id: "https://uor.foundation/homology/targetGroup",
            label: "targetGroup",
            comment: "The target chain group C_{k-1} of this boundary operator.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/BoundaryOperator"),
            range: "https://uor.foundation/homology/ChainGroup",
        },
        Property {
            id: "https://uor.foundation/homology/satisfiesBoundarySquaredZero",
            label: "satisfiesBoundarySquaredZero",
            comment: "Whether this boundary operator satisfies the fundamental property \
                      \u{2202}\u{00b2} = 0.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/BoundaryOperator"),
            range: XSD_BOOLEAN,
        },
        Property {
            id: "https://uor.foundation/homology/hasChainGroup",
            label: "hasChainGroup",
            comment: "A chain group belonging to this chain complex.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/ChainComplex"),
            range: "https://uor.foundation/homology/ChainGroup",
        },
        Property {
            id: "https://uor.foundation/homology/hasBoundary",
            label: "hasBoundary",
            comment: "A boundary operator belonging to this chain complex.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/ChainComplex"),
            range: "https://uor.foundation/homology/BoundaryOperator",
        },
        Property {
            id: "https://uor.foundation/homology/homologyDegree",
            label: "homologyDegree",
            comment: "The degree k of this homology group H_k.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/HomologyGroup"),
            range: XSD_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/bettiNumber",
            label: "bettiNumber",
            comment: "The Betti number \u{03b2}_k = rank(H_k): the rank of this homology group.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/HomologyGroup"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        // Amendment 54: Higher homotopy properties
        Property {
            id: "https://uor.foundation/homology/kanWitness",
            label: "kanWitness",
            comment: "A horn filler witnessing the Kan condition for this complex.",
            kind: PropertyKind::Object,
            functional: false,
            domain: Some("https://uor.foundation/homology/KanComplex"),
            range: "https://uor.foundation/homology/HornFiller",
        },
        Property {
            id: "https://uor.foundation/homology/hornDimension",
            label: "hornDimension",
            comment: "The dimension of the horn that this filler completes.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/HornFiller"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/hornPosition",
            label: "hornPosition",
            comment: "The position (missing face index) of the horn that this filler completes.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/HornFiller"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/truncationLevel",
            label: "truncationLevel",
            comment: "The truncation level k of this Postnikov truncation \u{03c4}\u{2264}k.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/PostnikovTruncation"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/truncationSource",
            label: "truncationSource",
            comment: "The KanComplex from which this Postnikov truncation is derived.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/PostnikovTruncation"),
            range: "https://uor.foundation/homology/KanComplex",
        },
        Property {
            id: "https://uor.foundation/homology/kInvariant",
            label: "kInvariant",
            comment: "The k-invariant classifying the extension at this truncation level.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/PostnikovTruncation"),
            range: "https://uor.foundation/homology/KInvariant",
        },
        Property {
            id: "https://uor.foundation/homology/kInvariantTrivial",
            label: "kInvariantTrivial",
            comment: "True iff this k-invariant is trivial, meaning the Postnikov truncation \
                      splits as a product.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/KInvariant"),
            range: XSD_BOOLEAN,
        },
        // Amendment 56: DeformationComplex properties
        Property {
            id: "https://uor.foundation/homology/deformationBase",
            label: "deformationBase",
            comment: "The CompleteType whose deformation complex this is.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/homology/DeformationComplex"),
            range: "https://uor.foundation/type/CompleteType",
        },
        Property {
            id: "https://uor.foundation/homology/tangentDimension",
            label: "tangentDimension",
            comment: "The dimension of the tangent space H\u{00b9}(Def(T)): the \
                      number of first-order deformations.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/DeformationComplex"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        Property {
            id: "https://uor.foundation/homology/obstructionDimension",
            label: "obstructionDimension",
            comment: "The dimension of the obstruction space H\u{00b2}(Def(T)): \
                      the number of independent obstructions to extending deformations.",
            kind: PropertyKind::Datatype,
            functional: true,
            domain: Some("https://uor.foundation/homology/DeformationComplex"),
            range: XSD_NON_NEGATIVE_INTEGER,
        },
        // --- Cross-namespace bridge properties (3) ---
        Property {
            id: "https://uor.foundation/homology/groundedIn",
            label: "groundedIn",
            comment: "The homology group that grounds this Betti number observable.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/observable/BettiNumber"),
            range: "https://uor.foundation/homology/HomologyGroup",
        },
        Property {
            id: "https://uor.foundation/homology/laplacianOf",
            label: "laplacianOf",
            comment: "The chain complex whose Laplacian determines this spectral gap.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/observable/SpectralGap"),
            range: "https://uor.foundation/homology/ChainComplex",
        },
        Property {
            id: "https://uor.foundation/homology/homologicalAnalysis",
            label: "homologicalAnalysis",
            comment: "The chain complex used for homological analysis of a resolution state.",
            kind: PropertyKind::Object,
            functional: true,
            domain: Some("https://uor.foundation/resolver/ResolutionState"),
            range: "https://uor.foundation/homology/ChainComplex",
        },
    ]
}

fn individuals() -> Vec<Individual> {
    vec![
        Individual {
            id: "https://uor.foundation/homology/boundarySquaredZero",
            type_: "https://uor.foundation/op/Identity",
            label: "boundarySquaredZero",
            comment: "\u{2202}\u{00b2} = 0: the boundary of a boundary is zero.",
            properties: &[
                (
                    "https://uor.foundation/op/lhs",
                    IndividualValue::Str("\u{2202}_k(\u{2202}_{k+1}(c))"),
                ),
                (
                    "https://uor.foundation/op/rhs",
                    IndividualValue::Str("0"),
                ),
                (
                    "https://uor.foundation/op/forAll",
                    IndividualValue::Str("c \u{2208} C_{k+1}"),
                ),

                (
                    "https://uor.foundation/op/verificationDomain",
                    IndividualValue::IriRef("https://uor.foundation/op/Topological"),
                ),
                (
                    "https://uor.foundation/op/verificationPathNote",
                    IndividualValue::Str("ChainComplex \u{2192} BoundaryOperator \u{2192} \u{2202}\u{00b2} = 0"),
                ),
            ],
        },
        Individual {
            id: "https://uor.foundation/homology/nerveFunctorN",
            type_: "https://uor.foundation/homology/NerveFunctor",
            label: "nerveFunctorN",
            comment: "The nerve functor N: constraints \u{2192} simplicial complex.",
            properties: &[],
        },
        Individual {
            id: "https://uor.foundation/homology/chainFunctorC",
            type_: "https://uor.foundation/homology/ChainFunctor",
            label: "chainFunctorC",
            comment: "The chain functor C: simplicial complex \u{2192} chain complex.",
            properties: &[],
        },
        Individual {
            id: "https://uor.foundation/homology/psi_4",
            type_: "https://uor.foundation/op/Identity",
            label: "psi_4",
            comment: "\u{03c8}_4: HomologyGroups \u{2192} BettiNumbers (extraction functor).",
            properties: &[
                (
                    "https://uor.foundation/op/lhs",
                    IndividualValue::Str("\u{03b2}_k(K)"),
                ),
                (
                    "https://uor.foundation/op/rhs",
                    IndividualValue::Str("rank(H_k(K))"),
                ),
                (
                    "https://uor.foundation/op/forAll",
                    IndividualValue::Str("simplicial complex K"),
                ),

                (
                    "https://uor.foundation/op/verificationDomain",
                    IndividualValue::IriRef("https://uor.foundation/op/Topological"),
                ),
                (
                    "https://uor.foundation/op/verificationPathNote",
                    IndividualValue::Str("HomologyGroup \u{2192} rank \u{2192} BettiNumber"),
                ),
            ],
        },
        Individual {
            id: "https://uor.foundation/homology/indexBridge",
            type_: "https://uor.foundation/op/Identity",
            label: "indexBridge",
            comment: "Index bridge: connects Euler characteristic to alternating Betti sum.",
            properties: &[
                (
                    "https://uor.foundation/op/lhs",
                    IndividualValue::Str("\u{03c7}(K)"),
                ),
                (
                    "https://uor.foundation/op/rhs",
                    IndividualValue::Str("\u{03a3}_k (-1)^k \u{03b2}_k"),
                ),
                (
                    "https://uor.foundation/op/forAll",
                    IndividualValue::Str("finite simplicial complex K"),
                ),

                (
                    "https://uor.foundation/op/verificationDomain",
                    IndividualValue::IriRef("https://uor.foundation/op/Topological"),
                ),
                (
                    "https://uor.foundation/op/verificationPathNote",
                    IndividualValue::Str("SimplicialComplex \u{2192} ChainComplex \u{2192} HomologyGroup \u{2192} BettiNumber \u{2192} alternating sum"),
                ),
            ],
        },
    ]
}
