// @generated by uor-crate from uor-ontology — do not edit manually

//! `resolver/` namespace — Type resolution strategies implementing the partition map Π : T_n → Part(R_n). Resolvers transform type declarations into ring partitions..
//!
//! Space: Bridge

use crate::enums::ComplexityClass;
use crate::enums::MetricAxis;
use crate::Primitives;

/// A strategy for resolving a type declaration into a partition of the ring. The kernel dispatches to a specific resolver based on the type's structure.
/// Disjoint with: ResolutionState, RefinementSuggestion.
pub trait Resolver<P: Primitives> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: crate::user::type_::TypeDefinition<P>;
    /// The type of input this resolver accepts.
    fn input_type(&self) -> &Self::TypeDefinition;
    /// Associated type for `Partition`.
    type Partition: crate::bridge::partition::Partition<P>;
    /// The type of output this resolver produces. For all UOR resolvers, the output is a partition:Partition.
    fn output_type(&self) -> &Self::Partition;
    /// Associated type for `ResolutionState`.
    type ResolutionState: ResolutionState<P>;
    /// The current resolution state of this resolver.
    fn resolution_state(&self) -> &Self::ResolutionState;
    /// The computational complexity class of this resolver. Replaces the string-valued resolver:complexity property.
    fn has_complexity_class(&self) -> ComplexityClass;
}

/// Resolves types by factoring the ring under dihedral group action. Identifies orbits under D_{2^n} to determine irreducibility boundaries.
pub trait DihedralFactorizationResolver<P: Primitives>: Resolver<P> {}

/// Resolves types by computing canonical forms via term rewriting. Applies the critical identity and normalization rules to reduce terms to unique canonical representatives.
pub trait CanonicalFormResolver<P: Primitives>: Resolver<P> {}

/// Resolves types by direct evaluation: applies operations to enumerate ring elements and classify them as irreducible, reducible, unit, or exterior.
pub trait EvaluationResolver<P: Primitives>: Resolver<P> {}

/// The current state of an iterative resolution: tracks how many iterations have been performed, whether the resolution is complete, and the current fiber deficit.
/// Disjoint with: Resolver, RefinementSuggestion.
pub trait ResolutionState<P: Primitives> {
    /// Whether this resolution is complete: all fibers are pinned and the partition is fully determined.
    fn is_complete(&self) -> P::Boolean;
    /// The number of refinement iterations performed so far.
    fn iteration_count(&self) -> P::NonNegativeInteger;
    /// Associated type for `FiberBudget`.
    type FiberBudget: crate::bridge::partition::FiberBudget<P>;
    /// The fiber budget showing the remaining unpinned fibers. When all fibers are pinned, the deficit is zero and resolution is complete.
    fn fiber_deficit(&self) -> &Self::FiberBudget;
    /// Associated type for `RefinementSuggestion`.
    type RefinementSuggestion: RefinementSuggestion<P>;
    /// A refinement suggestion for advancing this resolution.
    fn suggestion(&self) -> &[Self::RefinementSuggestion];
    /// The rate at which fibers are being pinned per iteration. A higher rate indicates faster convergence toward a complete resolution.
    fn convergence_rate(&self) -> P::Decimal;
    /// Associated type for `ConstraintNerve`.
    type ConstraintNerve: ConstraintNerve<P>;
    /// The constraint nerve associated with this resolution state.
    fn constraint_nerve(&self) -> &Self::ConstraintNerve;
    /// The residual Shannon entropy of the resolution state: S = freeCount × ln 2. Measures remaining uncertainty.
    fn residual_entropy(&self) -> P::Decimal;
    /// Whether all Betti numbers of the constraint nerve are zero, indicating no topological obstructions to resolution.
    fn topologically_complete(&self) -> P::Boolean;
    /// The Euler characteristic χ(N(C)) of the active constraint nerve at this resolution state. IT_7d requires this value to equal n (the quantum level) for resolution to be complete. Cached here to avoid recomputing the full ψ pipeline on each iteration check.
    fn nerve_euler_characteristic(&self) -> P::Integer;
}

/// A suggestion from the resolver for how to refine an incomplete resolution: which metric axis to explore, which class to narrow to, and which fibers to target.
/// Disjoint with: Resolver, ResolutionState.
pub trait RefinementSuggestion<P: Primitives> {
    /// The metric axis this suggestion recommends exploring.
    fn suggested_axis(&self) -> MetricAxis;
    /// The constraint class this suggestion recommends applying.
    fn suggested_class(&self) -> &P::String;
    /// Associated type for `FiberCoordinate`.
    type FiberCoordinate: crate::bridge::partition::FiberCoordinate<P>;
    /// The fiber coordinates this suggestion targets for pinning.
    fn target_fibers(&self) -> &[Self::FiberCoordinate];
}

/// The simplicial complex whose vertices are constraints and where a k-simplex exists iff the corresponding k+1 constraints have nonempty intersection. The nerve's topology governs resolution convergence: trivial homology ↔ smooth convergence, non-trivial homology ↔ potential stalls.
pub trait ConstraintNerve<P: Primitives>: crate::bridge::homology::SimplicialComplex<P> {}

/// O(1) complexity — the resolver runs in constant time regardless of ring size.
pub mod constant_time {}

/// O(log n) complexity — the resolver runs in logarithmic time in the quantum level.
pub mod logarithmic_time {}

/// O(n) complexity — the resolver runs in time linear in the quantum level.
pub mod linear_time {}

/// O(2^n) complexity — the resolver runs in time exponential in the quantum level.
pub mod exponential_time {}
