// @generated by uor-crate from uor-ontology — do not edit manually

//! `morphism/` namespace — Runtime abstractions for maps between UOR objects: transforms, isometries, embeddings, and group actions. The foundation provides the vocabulary; Prism writes the sentences..
//!
//! Space: User

use crate::Primitives;

/// A map between UOR objects. The root abstraction: source, target, and optionally what structure (if any) is preserved. This is what cert:TransformCertificate certifies.
/// Disjoint with: CompositionLaw.
pub trait Transform<P: Primitives> {
    /// The domain of the transform.
    fn source(&self) -> &P::String;
    /// The codomain of the transform.
    fn target(&self) -> &P::String;
    /// The structure preserved by this transform (if any). E.g., a ring homomorphism preserves addition and multiplication.
    fn preserves_count(&self) -> usize;
    /// Associated type for `ComputationTrace`.
    type ComputationTrace: crate::bridge::trace::ComputationTrace<P>;
    /// The computation trace that realized this transform at runtime. A Transform is an abstraction; a trace is the kernel's record of how it was executed via concrete operations.
    fn trace(&self) -> &Self::ComputationTrace;
    /// Associated type for `Transform`.
    type TransformTarget: Transform<P>;
    /// A transform that this transform can be composed with. The target of this transform must match the source of the composed transform.
    fn composes_with(&self) -> &[Self::TransformTarget];
    /// A human-readable description of the structure this transform preserves (e.g., 'ring homomorphism', 'metric isometry').
    fn preserves_structure(&self) -> &P::String;
}

/// A transform that preserves metric structure with respect to a specified metric. In UOR, isometry is metric-relative: neg is a ring isometry, bnot is a Hamming isometry. A transform can be an isometry with respect to one metric but not the other. This is what cert:IsometryCertificate certifies.
/// Disjoint with: Composition.
pub trait Isometry<P: Primitives>: Transform<P> {
    /// Associated type for `MetricObservable`.
    type MetricObservable: crate::bridge::observable::MetricObservable<P>;
    /// The specific metric this isometry preserves. Points to observable:RingMetric or observable:HammingMetric. A transform that preserves both is an isometry of the full UOR geometry. A transform that preserves one but not the other has nontrivial curvature — observable:CurvatureObservable measures this gap.
    fn preserves_metric(&self) -> &[Self::MetricObservable];
}

/// An injective, structure-preserving transform across quantum levels. The canonical instance is the level embedding ι : R_n → R_{n'} (n < n'), which preserves addition, multiplication, and content addressing.
/// Disjoint with: Composition.
pub trait Embedding<P: Primitives>: Transform<P> {
    /// The quantum level n of the source ring for an embedding.
    fn source_quantum(&self) -> P::PositiveInteger;
    /// The quantum level n' of the target ring for an embedding. Must satisfy n' > n (embeddings go to larger rings).
    fn target_quantum(&self) -> P::PositiveInteger;
    /// Associated type for `Identity`.
    type Identity: crate::kernel::op::Identity<P>;
    /// Certificate that this embedding's addressing diagram commutes: glyph ∘ ι ∘ addresses is well-defined and injective.
    fn address_coherence(&self) -> &Self::Identity;
}

/// The mechanism by which a group applies transforms systematically to a set. Each group element induces a transform of the set. The dihedral action on type space is an action by isometries — every element of D_{2^n} produces an isometric transform of 𝒯_n.
pub trait Action<P: Primitives> {
    /// Associated type for `Group`.
    type Group: crate::kernel::op::Group<P>;
    /// The group acting in this group action.
    fn group(&self) -> &Self::Group;
    /// The set being acted upon by this group action.
    fn acting_on(&self) -> &P::String;
    /// Whether every transform induced by this action is an isometry. True for the dihedral action on 𝒯_n (Frame Theorem).
    fn action_isometry(&self) -> P::Boolean;
}

/// A transform formed by composing two or more transforms sequentially. The categorical composition operation that turns transforms into a category.
/// Disjoint with: Isometry, Embedding, Identity.
pub trait Composition<P: Primitives>: Transform<P> {
    /// Associated type for `Transform`.
    type Transform: Transform<P>;
    /// The transform that results from this composition.
    fn composition_result(&self) -> &Self::Transform;
    /// A component transform of this composition.
    fn composition_components(&self) -> &[Self::Transform];
}

/// The identity transform on a type: maps every element to itself. The categorical identity morphism.
/// Disjoint with: Composition.
pub trait Identity<P: Primitives>: Transform<P> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: crate::user::type_::TypeDefinition<P>;
    /// The type on which this identity transform acts.
    fn identity_on(&self) -> &Self::TypeDefinition;
}

/// A law governing how operations compose. Records whether the composition is associative, commutative, and what the result operation is. The critical composition law (neg ∘ bnot = succ) is the foundational instance.
/// Disjoint with: Transform.
pub trait CompositionLaw<P: Primitives> {
    /// Whether this composition law is associative.
    fn is_associative(&self) -> P::Boolean;
    /// Whether this composition law is commutative.
    fn is_commutative(&self) -> P::Boolean;
    /// Associated type for `Operation`.
    type Operation: crate::kernel::op::Operation<P>;
    /// An operation that is a component of this composition law.
    fn law_components(&self) -> &[Self::Operation];
    /// The operation that results from this composition law.
    fn law_result(&self) -> &Self::Operation;
}

/// A Transform mapping a surface symbol (any schema:Literal) to its ring datum (a schema:Datum) via the content-addressing bijection. Typed, derivation-witnessed, constraint-preserving map from surface to coordinate. Applies identically across NLP tokens, ARC-AGI grid cells, MIDI notes, pixels, sensor readings, and logical propositions.
/// Disjoint with: ProjectionMap.
pub trait GroundingMap<P: Primitives>: Transform<P> {
    /// Associated type for `Literal`.
    type Literal: crate::kernel::schema::Literal<P>;
    /// The surface symbol that is the source of this grounding.
    fn surface_symbol(&self) -> &Self::Literal;
    /// Associated type for `Address`.
    type Address: crate::kernel::address::Address<P>;
    /// The resolved ring address that is the target of this grounding.
    fn grounded_address(&self) -> &Self::Address;
    /// Associated type for `Derivation`.
    type Derivation: crate::bridge::derivation::Derivation<P>;
    /// The derivation witnessing the content-addressing computation that produced the grounded address from the surface symbol.
    fn grounding_derivation(&self) -> &Self::Derivation;
    /// Associated type for `Constraint`.
    type Constraint: crate::user::type_::Constraint<P>;
    /// A typed attribute preserved by this grounding. Non-functional: one assertion per active constraint axis (vertical, horizontal, diagonal).
    fn symbol_constraints(&self) -> &[Self::Constraint];
}

/// A Transform mapping a resolved partition:Partition (address neighbourhood) to an ordered sequence of surface symbols. Output ordering determined by the active state:Frame — the same constraint frame that decomposed the input symbol sequence.
/// Disjoint with: GroundingMap.
pub trait ProjectionMap<P: Primitives>: Transform<P> {
    /// Associated type for `Frame`.
    type Frame: crate::user::state::Frame<P>;
    /// The active frame — shared with the grounding that produced the query. The shared-frame condition (Surface Symmetry Theorem) requires G and P to reference the same frame.
    fn projection_frame(&self) -> &Self::Frame;
    /// Associated type for `Partition`.
    type Partition: crate::bridge::partition::Partition<P>;
    /// The resolved partition (address neighbourhood) that this map projects back to surface symbols.
    fn projection_source(&self) -> &Self::Partition;
    /// Associated type for `CompositeConstraint`.
    type CompositeConstraint: crate::user::type_::CompositeConstraint<P>;
    /// Ordering constraint determining the output symbol sequence. Domain-specific: syntactic position (NLP), row-major scan (ARC), temporal sequence (music).
    fn projection_order(&self) -> &Self::CompositeConstraint;
    /// Completeness criterion: does projecting the grounded source address recover a symbol in the same type class as the input? True iff the shared-frame condition holds.
    fn round_trip_coherence(&self) -> P::Boolean;
}

/// A certificate attesting that a specific grounding round-trip (P∘Π∘G) satisfied the shared-frame condition and landed in the type-equivalent neighbourhood of the source symbol. Witnesses the Surface Symmetry Theorem (op:surfaceSymmetry) for one specific symbol instance.
pub trait GroundingCertificate<P: Primitives>: crate::bridge::cert::Certificate<P> {
    /// Associated type for `GroundingMap`.
    type GroundingMap: GroundingMap<P>;
    /// The GroundingMap used in this certified round-trip.
    fn grounding_cert_map(&self) -> &Self::GroundingMap;
    /// Associated type for `ProjectionMap`.
    type ProjectionMap: ProjectionMap<P>;
    /// The ProjectionMap used in this certified round-trip.
    fn grounding_cert_projection(&self) -> &Self::ProjectionMap;
    /// Associated type for `Literal`.
    type Literal: crate::kernel::schema::Literal<P>;
    /// The surface symbol that entered the grounding boundary.
    fn grounding_cert_source_symbol(&self) -> &Self::Literal;
    /// Associated type for `Address`.
    type Address: crate::kernel::address::Address<P>;
    /// The ring address the symbol was grounded to.
    fn grounding_cert_address(&self) -> &Self::Address;
}

/// A topological delta: records changes in topological invariants (Betti numbers, Euler characteristic, nerve structure) before and after a morphism.
pub trait TopologicalDelta<P: Primitives> {
    /// Associated type for `BettiNumber`.
    type BettiNumber: crate::bridge::observable::BettiNumber<P>;
    /// Betti numbers before the morphism.
    fn bettis_before(&self) -> &Self::BettiNumber;
    /// Betti numbers after the morphism.
    fn bettis_after(&self) -> &Self::BettiNumber;
    /// Euler characteristic before the morphism.
    fn euler_before(&self) -> P::Integer;
    /// Euler characteristic after the morphism.
    fn euler_after(&self) -> P::Integer;
    /// Associated type for `SimplicialComplex`.
    type SimplicialComplex: crate::bridge::homology::SimplicialComplex<P>;
    /// Constraint nerve (simplicial complex) before the morphism.
    fn nerve_before(&self) -> &Self::SimplicialComplex;
    /// Constraint nerve (simplicial complex) after the morphism.
    fn nerve_after(&self) -> &Self::SimplicialComplex;
}

/// The critical composition law: neg ∘ bnot = succ. This is the operational form of the critical identity theorem. The composition of the two involutions (neg, bnot) yields the successor operation. Non-associative and non-commutative.
pub mod critical_composition {
    /// `isAssociative`
    pub const IS_ASSOCIATIVE: bool = false;
    /// `isCommutative`
    pub const IS_COMMUTATIVE: bool = false;
    /// `lawComponents`
    pub const LAW_COMPONENTS: &[&str] = &[
        "https://uor.foundation/op/neg",
        "https://uor.foundation/op/bnot",
    ];
    /// `lawResult` -> `succ`
    pub const LAW_RESULT: &str = "https://uor.foundation/op/succ";
}
