// @generated by uor-crate from uor-ontology — do not edit manually

//! `type/` namespace — Runtime type declarations that parameterize the resolution pipeline. Types are declared by Prism applications and resolved to partitions of the ring..
//!
//! Space: User

use crate::enums::MetricAxis;
use crate::enums::QuantumLevel;
use crate::Primitives;

/// A runtime type declaration. The root class for all UOR types. Each TypeDefinition, when resolved, produces a partition of the ring at the specified quantum level.
/// Disjoint with: Constraint, MetricAxis.
pub trait TypeDefinition<P: Primitives> {
    /// Associated type for `Address`.
    type Address: crate::kernel::address::Address<P>;
    /// The content-derived address of this type definition, uniquely identifying the type in the UOR address space.
    fn content_address(&self) -> &Self::Address;
}

/// A primitive type defined by a fixed bit width. The carrier is the entire ring Z/(2^n)Z at the specified quantum level.
pub trait PrimitiveType<P: Primitives>: TypeDefinition<P> {
    /// The bit width of a primitive type (the quantum level n). The carrier is Z/(2^n)Z.
    fn bit_width(&self) -> P::PositiveInteger;
}

/// A product (Cartesian) type formed from multiple component types. The carrier is the product of the component carriers.
pub trait ProductType<P: Primitives>: TypeDefinition<P> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: TypeDefinition<P>;
    /// A component type in a product type.
    fn component(&self) -> &[Self::TypeDefinition];
}

/// A sum (disjoint union) type formed from multiple variant types. The carrier is the disjoint union of the variant carriers.
pub trait SumType<P: Primitives>: TypeDefinition<P> {}

/// A type formed by constraining a base type with a predicate. The carrier is the subset of the base carrier satisfying the constraint.
pub trait ConstrainedType<P: Primitives>: TypeDefinition<P> {
    /// Associated type for `TypeDefinition`.
    type TypeDefinition: TypeDefinition<P>;
    /// The base type that a constrained type restricts.
    fn base_type(&self) -> &Self::TypeDefinition;
    /// Associated type for `Constraint`.
    type Constraint: Constraint<P>;
    /// A typed constraint object applied to this constrained type. Replaces the deprecated string-based type:constraint property.
    fn has_constraint(&self) -> &[Self::Constraint];
    /// Associated type for `HolonomyGroup`.
    type HolonomyGroup: crate::bridge::observable::HolonomyGroup<P>;
    /// The HolonomyGroup of this type. Computed by the MonodromyResolver.
    fn holonomy_group(&self) -> &Self::HolonomyGroup;
    /// Associated type for `MonodromyClass`.
    type MonodromyClass: crate::bridge::observable::MonodromyClass<P>;
    /// The MonodromyClass classifying this type as flat or twisted.
    fn monodromy_class(&self) -> &Self::MonodromyClass;
    /// Whether this ConstrainedType has been classified as FlatType or TwistedType by the MonodromyResolver. The MN_8 identity guarantees this is a bivalent classification: holonomyClassified(T) iff isFlatType(T) xor isTwistedType(T).
    fn holonomy_classified(&self) -> P::Boolean;
}

/// A composable predicate that refines a type by pinning one or more fiber coordinates. Constraints are the parameterization mechanism for ConstrainedType.
/// Disjoint with: TypeDefinition, MetricAxis.
pub trait Constraint<P: Primitives> {
    /// The metric axis along which this constraint operates: vertical (ring), horizontal (Hamming), or diagonal (incompatibility).
    fn metric_axis(&self) -> MetricAxis;
    /// Associated type for `FiberCoordinate`.
    type FiberCoordinate: crate::bridge::partition::FiberCoordinate<P>;
    /// A fiber coordinate that this constraint pins when applied.
    fn pins_fibers(&self) -> &[Self::FiberCoordinate];
    /// The cost of applying this constraint in terms of axis crossings: the number of metric boundaries that must be traversed.
    fn crossing_cost(&self) -> P::NonNegativeInteger;
}

/// A constraint based on residue class membership: x ≡ r (mod m). Pins fibers corresponding to the residue pattern.
/// Disjoint with: CarryConstraint, DepthConstraint, CompositeConstraint, HammingConstraint, FiberConstraint, AffineConstraint.
pub trait ResidueConstraint<P: Primitives>: Constraint<P> {
    /// The modulus m of a residue constraint: x ≡ r (mod m).
    fn modulus(&self) -> P::PositiveInteger;
    /// The residue value r of a residue constraint: x ≡ r (mod m).
    fn residue(&self) -> P::NonNegativeInteger;
}

/// A constraint based on carry propagation patterns in ring arithmetic. Pins fibers corresponding to carry positions.
/// Disjoint with: ResidueConstraint, DepthConstraint, CompositeConstraint, HammingConstraint, FiberConstraint, AffineConstraint.
pub trait CarryConstraint<P: Primitives>: Constraint<P> {
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<P>;
    /// The carry propagation pattern of a carry constraint, expressed as a Datum at the appropriate quantum level.
    fn carry_pattern(&self) -> &Self::Datum;
}

/// A constraint on factorization depth: the minimum and maximum number of irreducible factors. Pins fibers by bounding the factorization tree depth.
/// Disjoint with: ResidueConstraint, CarryConstraint, CompositeConstraint, HammingConstraint, FiberConstraint, AffineConstraint.
pub trait DepthConstraint<P: Primitives>: Constraint<P> {
    /// The minimum factorization depth required by a depth constraint.
    fn min_depth(&self) -> P::NonNegativeInteger;
    /// The maximum factorization depth allowed by a depth constraint.
    fn max_depth(&self) -> P::NonNegativeInteger;
}

/// A constraint formed by composing two or more simpler constraints. The composite pins the union of fibers pinned by its components.
/// Disjoint with: ResidueConstraint, CarryConstraint, DepthConstraint, HammingConstraint, FiberConstraint, AffineConstraint.
pub trait CompositeConstraint<P: Primitives>: Constraint<P> {
    /// Associated type for `Constraint`.
    type Constraint: Constraint<P>;
    /// A component constraint of this composite constraint.
    fn composed_from(&self) -> &[Self::Constraint];
}

/// Pins the Hamming weight of the Datum to at most the bound. The horizontal axis of the tri-metric.
/// Disjoint with: ResidueConstraint, CarryConstraint, DepthConstraint, CompositeConstraint, FiberConstraint, AffineConstraint.
pub trait HammingConstraint<P: Primitives>: Constraint<P> {
    /// Upper bound on the Hamming weight of the Datum.
    fn hamming_bound(&self) -> P::NonNegativeInteger;
}

/// Pins a single fiber coordinate to 0 or 1. The atomic unit of the fiber budget.
/// Disjoint with: ResidueConstraint, CarryConstraint, DepthConstraint, CompositeConstraint, HammingConstraint, AffineConstraint.
pub trait FiberConstraint<P: Primitives>: Constraint<P> {
    /// Zero-based index of the pinned fiber coordinate.
    fn fiber_index(&self) -> P::NonNegativeInteger;
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<P>;
    /// The value the pinned fiber coordinate must equal (a Datum in the set {0, 1}).
    fn fiber_value(&self) -> &Self::Datum;
}

/// Pins the Datum to an affine subspace specified by an offset and a set of generators.
/// Disjoint with: ResidueConstraint, CarryConstraint, DepthConstraint, CompositeConstraint, HammingConstraint, FiberConstraint.
pub trait AffineConstraint<P: Primitives>: Constraint<P> {
    /// Associated type for `Datum`.
    type Datum: crate::kernel::schema::Datum<P>;
    /// Constant offset defining the affine subspace.
    fn affine_offset(&self) -> &Self::Datum;
    /// A generator of the affine subspace. Non-functional: multiple generators span the subspace.
    fn affine_generator(&self) -> &[Self::Datum];
}

/// A TypeDefinition certified to satisfy the UOR completeness criterion (IT_7d): its constraint nerve N(C) has Euler characteristic χ = n and all Betti numbers β_k = 0. A CompleteType guarantees that resolution closes the fiber budget in O(1) — no iterative refinement is required. Completeness is attested by a cert:CompletenessCertificate linked via cert:certifiedType. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
pub trait CompleteType<P: Primitives>: TypeDefinition<P> {}

/// A ConstrainedType actively undergoing the completeness certification pipeline. Links to the resolver:ResolutionState tracking the current iteration and to the resolver:ConstraintNerve being computed. Disjoint from CompleteType (which is already certified). This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
/// Disjoint with: CompleteType.
pub trait CompletenessCandidate<P: Primitives>: ConstrainedType<P> {
    /// Associated type for `ConstrainedType`.
    type ConstrainedType: ConstrainedType<P>;
    /// The ConstrainedType being evaluated for completeness by this CompletenessCandidate.
    fn completeness_candidate(&self) -> &[Self::ConstrainedType];
    /// Associated type for `ConstraintNerve`.
    type ConstraintNerve: crate::bridge::resolver::ConstraintNerve<P>;
    /// The constraint nerve being computed for this candidate. The CompletenessResolver reads χ(N(C)) from this nerve at each iteration via resolver:nerveEulerCharacteristic.
    fn candidate_nerve(&self) -> &Self::ConstraintNerve;
}

/// A record of a single fiber-closing event: one constraint application that reduced the FiberBudget deficit. Carries the applied constraint and the fibersClosed count. Forms the ordered audit trail between ConstrainedType and CompleteType.
pub trait CompletenessWitness<P: Primitives> {
    /// Associated type for `Constraint`.
    type Constraint: Constraint<P>;
    /// The constraint applied in this witness step.
    fn witness_constraint(&self) -> &Self::Constraint;
    /// Number of fibers closed by this witness step.
    fn fibers_closed(&self) -> P::NonNegativeInteger;
}

/// A specification of the desired topological properties of a type to be synthesised. Carries a target Euler characteristic (targetEulerCharacteristic) and a target Betti profile (zero or more targetBettiNumber assertions). The minimal goal for O(1) resolution is: targetEulerCharacteristic = n and all targetBettiNumber = 0 — the IT_7d profile.
pub trait TypeSynthesisGoal<P: Primitives> {
    /// The target χ(N(C)) value. For O(1) resolution: set equal to n (the quantum level).
    fn target_euler_characteristic(&self) -> P::Integer;
    /// Non-functional. Each assertion specifies a target Betti number value for a given homological degree. Multiple assertions permitted, one per degree.
    fn target_betti_number(&self) -> &[P::NonNegativeInteger];
    /// Whether the target signature of this TypeSynthesisGoal is a ForbiddenSignature. If true, synthesis is provably impossible.
    fn target_forbidden(&self) -> P::Boolean;
}

/// The output of a TypeSynthesisResolver run. Contains the SynthesizedType, the realised topological signature (as a SynthesisSignature), and the SynthesisTrace recording the construction steps.
pub trait TypeSynthesisResult<P: Primitives> {}

/// A ConstrainedType produced by the TypeSynthesisResolver. Distinguished from a hand-authored ConstrainedType by the presence of a type:synthesisResult link. May or may not be a CompleteType, depending on the synthesis goal. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
pub trait SynthesizedType<P: Primitives>: ConstrainedType<P> {
    /// Associated type for `TypeSynthesisResult`.
    type TypeSynthesisResult: TypeSynthesisResult<P>;
    /// Links a SynthesizedType back to the synthesis run that produced it.
    fn synthesis_result(&self) -> &Self::TypeSynthesisResult;
}

/// The minimal set of constraints in the SynthesizedType's constraint set that is sufficient to realise the target topological signature. The minimality criterion is that removing any single member changes the realised signature.
pub trait MinimalConstraintBasis<P: Primitives> {
    /// Associated type for `Constraint`.
    type Constraint: Constraint<P>;
    /// Non-functional. One assertion per constraint in the minimal basis.
    fn basis_constraint(&self) -> &[Self::Constraint];
    /// The cardinality of the minimal basis. The theoretical lower bound is n (one constraint per fiber).
    fn basis_size(&self) -> P::NonNegativeInteger;
}

/// A ConstrainedType T' over R_{n+1} obtained by extending a ConstrainedType T over R_n. Carries a link to the base type (liftBase), the quantum level it lifts to (liftTargetLevel), and the LiftObstruction (if the lift fails to transfer completeness). A QuantumLift is a CompleteType iff its LiftObstruction is trivial.
pub trait QuantumLift<P: Primitives> {
    /// Associated type for `ConstrainedType`.
    type ConstrainedType: ConstrainedType<P>;
    /// The base type being lifted to the next quantum level.
    fn lift_base(&self) -> &Self::ConstrainedType;
    /// The quantum level this lift targets.
    fn lift_target_level(&self) -> QuantumLevel;
    /// Associated type for `LiftObstruction`.
    type LiftObstruction: LiftObstruction<P>;
    /// The LiftObstruction for this lift. Trivial (zero class) iff the lift inherits completeness.
    fn lift_obstruction(&self) -> &Self::LiftObstruction;
}

/// The algebraic obstruction to a QuantumLift inheriting the completeness of its base type. Computed as the image of the spectral sequence differential d_2. If trivial (zero), the base type's completeness lifts. If non-trivial, at least one additional constraint is needed at the new quantum level.
pub trait LiftObstruction<P: Primitives> {
    /// True iff the obstruction class is zero — the base type's completeness transfers to the lifted quantum level without additional constraints.
    fn obstruction_trivial(&self) -> P::Boolean;
    /// Associated type for `FiberCoordinate`.
    type FiberCoordinate: crate::bridge::partition::FiberCoordinate<P>;
    /// The fiber at the new quantum level where the obstruction is located. Ranges over the new bit position introduced at Q_{n+1}.
    fn obstruction_fiber(&self) -> &Self::FiberCoordinate;
}

/// A ConstrainedType whose HolonomyGroup is non-trivial — at least one closed constraint path produces a non-identity dihedral element. A TwistedType may still be a CompleteType (IT_7d is a homological, not holonomic, criterion), but its resolution paths require tracking dihedral accumulation. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
/// Disjoint with: FlatType.
pub trait TwistedType<P: Primitives>: ConstrainedType<P> {}

/// A ConstrainedType whose HolonomyGroup is trivial — all closed constraint paths have identity monodromy. The constraint configuration is topologically flat: resolution is path-independent. This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
/// Disjoint with: TwistedType.
pub trait FlatType<P: Primitives>: ConstrainedType<P> {}

/// A type representing a superposition of fiber states where fibers carry complex amplitudes rather than binary pinned/free assignments. Ontological realisation of RC_5 (Amendment 32). This class is not addressable from a type-expr position in the term language; references from term-language positions are rejected by the resolver.
pub trait SuperposedFiberState<P: Primitives>: TypeDefinition<P> {
    /// The amplitude coefficient for this superposed fiber state.
    fn amplitude(&self) -> P::Decimal;
    /// Whether the amplitude vector of this SuperposedFiberState satisfies the normalization condition Σ|αᵢ|² = 1 (QM_5). Set by the SuperpositionResolver after verification.
    fn normalization_verified(&self) -> P::Boolean;
}

/// A topological signature (χ, β_k) that is formally impossible to achieve for any ConstrainedType. Witnessed by an ImpossibilityWitness in proof/.
pub trait ForbiddenSignature<P: Primitives> {}

/// A fiber state that has undergone projective collapse from a SuperposedFiberState to a definitive classical value. Topologically equivalent to a classically pinned fiber (QM_2).
pub trait CollapsedFiberState<P: Primitives> {
    /// Associated type for `SuperposedFiberState`.
    type SuperposedFiberState: SuperposedFiberState<P>;
    /// The SuperposedFiberState from which this CollapsedFiberState was produced by projective measurement.
    fn collapsed_from(&self) -> &Self::SuperposedFiberState;
    /// The amplitude of the surviving branch after projective collapse. |α|² is the probability of this outcome under the Born rule.
    fn surviving_amplitude(&self) -> P::Decimal;
}

/// An ordered composition of QuantumLift steps from liftSourceLevel (Q_j) to liftTargetLevel (Q_k) for any j < k. The canonical object certifying type completeness at arbitrary Q_k.
pub trait LiftChain<P: Primitives> {
    /// The quantum level at the base of the chain.
    fn lift_source_level(&self) -> QuantumLevel;
    /// The number of QuantumLift steps in the chain (k - j).
    fn chain_length(&self) -> P::NonNegativeInteger;
    /// Associated type for `QuantumLift`.
    type QuantumLift: QuantumLift<P>;
    /// A QuantumLift step in this chain. Non-functional: one per step.
    fn chain_step(&self) -> &[Self::QuantumLift];
    /// Associated type for `ObstructionChain`.
    type ObstructionChain: ObstructionChain<P>;
    /// The full obstruction history of this chain.
    fn chain_obstruction_profile(&self) -> &Self::ObstructionChain;
    /// The basis size of the CompleteType at the chain target level.
    fn resolved_basis_size(&self) -> P::NonNegativeInteger;
}

/// The complete ordered sequence of LiftObstruction records encountered and resolved along a LiftChain. An empty ObstructionChain means the tower is flat.
pub trait ObstructionChain<P: Primitives> {
    /// Associated type for `LiftObstruction`.
    type LiftObstruction: LiftObstruction<P>;
    /// A non-trivial LiftObstruction in this chain. Non-functional.
    fn obstruction_at(&self) -> &[Self::LiftObstruction];
    /// Total number of non-trivial LiftObstruction records.
    fn obstruction_count(&self) -> P::NonNegativeInteger;
    /// True iff obstructionCount = 0 (flat tower).
    fn is_flat(&self) -> P::Boolean;
}

/// The space of all CompleteTypes over R_n at a given quantum level.
pub trait ModuliSpace<P: Primitives> {
    /// The quantum level at which this moduli space is defined.
    fn moduli_quantum_level(&self) -> QuantumLevel;
    /// Associated type for `CompleteType`.
    type CompleteType: CompleteType<P>;
    /// A CompleteType that is a point of this moduli space.
    fn moduli_point(&self) -> &[Self::CompleteType];
    /// The dimension of this moduli space.
    fn moduli_dimension(&self) -> P::NonNegativeInteger;
}

/// A stratum indexed by a conjugacy class of subgroups of D_{2^n}.
pub trait HolonomyStratum<P: Primitives> {
    /// Associated type for `MonodromyClass`.
    type MonodromyClass: crate::bridge::observable::MonodromyClass<P>;
    /// The MonodromyClass indexing this stratum.
    fn stratum_holonomy_class(&self) -> &Self::MonodromyClass;
    /// The codimension of this stratum within the moduli space.
    fn stratum_codimension(&self) -> P::NonNegativeInteger;
    /// Associated type for `ModuliSpace`.
    type ModuliSpace: ModuliSpace<P>;
    /// The moduli space containing this stratum.
    fn stratum_moduli(&self) -> &Self::ModuliSpace;
}

/// A one-parameter family of constraint configurations parameterizing a path.
pub trait DeformationFamily<P: Primitives> {
    /// Associated type for `CompleteType`.
    type CompleteType: CompleteType<P>;
    /// A CompleteType along the deformation path.
    fn family_parameter(&self) -> &[Self::CompleteType];
    /// Whether every member of this deformation family remains a CompleteType.
    fn family_preserves_completeness(&self) -> P::Boolean;
}

/// The versal deformation of a CompleteType T.
pub trait VersalDeformation<P: Primitives> {
    /// Associated type for `CompleteType`.
    type CompleteType: CompleteType<P>;
    /// The CompleteType at the base of this versal deformation.
    fn versal_base(&self) -> &Self::CompleteType;
    /// The dimension of the versal deformation space.
    fn versal_dimension(&self) -> P::NonNegativeInteger;
}

/// The map induced by QuantumLift from one moduli space to the next.
pub trait ModuliTowerMap<P: Primitives> {
    /// Associated type for `ModuliSpace`.
    type ModuliSpace: ModuliSpace<P>;
    /// The source moduli space of this tower map.
    fn tower_map_source(&self) -> &Self::ModuliSpace;
}

/// The adjunction between the type lattice and the fiber lattice. The upper adjoint is type closure; the lower adjoint is fiber interior. σ = lower adjoint evaluation; r = complement of upper adjoint image.
pub trait GaloisConnection<P: Primitives> {
    /// Associated type for `TermExpression`.
    type TermExpression: crate::kernel::schema::TermExpression<P>;
    /// The upper adjoint (type closure) of the Galois connection, expressed as a symbolic formula string.
    fn upper_adjoint(&self) -> &Self::TermExpression;
    /// The lower adjoint (fiber interior) of the Galois connection, expressed as a symbolic formula string.
    fn lower_adjoint(&self) -> &Self::TermExpression;
    /// The fixpoint condition for the Galois connection: when upper(lower(T)) = T, the type is complete.
    fn fixpoint_condition(&self) -> &Self::TermExpression;
    /// Description of the refinement direction: ascending in type lattice corresponds to descending in fiber freedom.
    fn refinement_direction(&self) -> P::NonNegativeInteger;
    /// The closure property of a Galois connection.
    fn galois_closure_property(&self) -> &Self::TermExpression;
    /// The interior property of a Galois connection.
    fn galois_interior_property(&self) -> &Self::TermExpression;
}

/// A morphism T₁ → T₂ witnessing that T₁ is a subtype of T₂: the constraint set of T₁ is a superset of the constraint set of T₂.
pub trait TypeInclusion<P: Primitives>: crate::user::morphism::Transform<P> {
    /// Associated type for `ConstrainedType`.
    type ConstrainedType: ConstrainedType<P>;
    /// The subtype (more constraints).
    fn inclusion_source(&self) -> &Self::ConstrainedType;
    /// The supertype (fewer constraints).
    fn inclusion_target(&self) -> &Self::ConstrainedType;
    /// True iff constraints(source) ⊇ constraints(target). Computed, not asserted.
    fn inclusion_witness(&self) -> P::Boolean;
}

/// The partial order on types induced by TypeInclusion. The top element is PrimitiveType (no constraints); the bottom elements are CompleteTypes (all fibers pinned).
pub trait SubtypingLattice<P: Primitives> {
    /// Maximum chain length from PrimitiveType (top) to any CompleteType (bottom). Equals the fiber budget n at quantum level Q_k.
    fn lattice_depth(&self) -> P::NonNegativeInteger;
}

/// A single value from an ordered domain. fiberCount = n (quantization bits).
pub mod scalar_type {
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "n (quantization bits)";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str =
        "quantize(value, range, bits) produces ring element where d_R reflects value proximity";
}

/// A value from a finite unordered set. fiberCount = ceil(log2(|alphabet|)).
pub mod symbol_type {
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "ceil(log2(|alphabet|))";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str =
        "argmin_{encoding} sum d_delta over observed pairs (CY_5)";
}

/// An ordered list of elements with backbone constraint. The free monoid on the element type.
pub mod sequence_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "backbone ordering: elements indexed by position";
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "sum of element fiber counts";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "free monoid on element type, backbone constraint";
}

/// A fixed collection of named fields.
pub mod tuple_type {
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "sum of field fiber counts";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "fiber ordering follows CY_6 (optimal fiber ordering)";
}

/// Nodes with edge constraints. Constraint nerve = graph topology.
pub mod graph_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "edge constraints: adjacency preserved under grounding";
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "sum of node fiber counts + edge overhead";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "constraint nerve = graph nerve, beta_k equality";
}

/// Unordered collection. d_delta is permutation-invariant.
pub mod set_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "permutation invariance: encoding is order-independent";
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "sum of element fiber counts";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str =
        "d_delta invariant under element permutation, D_{2n} symmetry";
}

/// Hierarchical structure. beta_1=0 (acyclic), beta_0=1 (connected).
pub mod tree_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "beta_1=0 (acyclic), beta_0=1 (connected)";
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "sum of node fiber counts";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "parent-child encoding with acyclicity constraint";
}

/// Collection of tuples sharing a schema = Sequence(Tuple(S)). Functorial decomposition.
pub mod table_type {
    /// `structuralConstraint`
    pub const STRUCTURAL_CONSTRAINT: &str = "shared schema: all rows conform to tuple type S";
    /// `structuralFiberCount`
    pub const STRUCTURAL_FIBER_COUNT: &str = "row_count * tuple_fiber_count";
    /// `structuralGrounding`
    pub const STRUCTURAL_GROUNDING: &str = "Sequence(Tuple(S)), functorial decomposition";
}

/// The structural position preserves TypeInclusion: if T₁ ≤ T₂, then F(T₁) ≤ F(T₂).
pub mod covariant {
    /// `enumVariant` -> `Covariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Covariant";
}

/// The structural position reverses TypeInclusion: if T₁ ≤ T₂, then F(T₂) ≤ F(T₁).
pub mod contravariant {
    /// `enumVariant` -> `Contravariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Contravariant";
}

/// The structural position requires exact type equality: F(T₁) ≤ F(T₂) only if T₁ = T₂.
pub mod invariant {
    /// `enumVariant` -> `Invariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Invariant";
}

/// The structural position ignores the type parameter: F(T₁) ≤ F(T₂) for all T₁, T₂.
pub mod bivariant {
    /// `enumVariant` -> `Bivariant`
    pub const ENUM_VARIANT: &str = "https://uor.foundation/type/Bivariant";
}

/// The canonical binary disjoint union type whose carrier is L + R.
pub mod either_type {}

/// The canonical A + Unit idiom for optional values.
pub mod option_type {}
